"""empty message

Revision ID: eef14c0112c5
Revises: 5b94e476df4e
Create Date: 2019-12-20 13:04:09.299786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eef14c0112c5'
down_revision = '5b94e476df4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('college', sa.String(length=200), nullable=True))
    op.add_column('user', sa.Column('dob', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('gender', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'gender')
    op.drop_column('user', 'dob')
    op.drop_column('user', 'college')
    # ### end Alembic commands ###
